# Generated by Django 6.0 on 2025-12-18 22:03

from django.db import migrations
import uuid


def populate_uuids(apps, schema_editor):
    Organization = apps.get_model('orgs', 'Organization')
    for org in Organization.objects.all():
        org.uuid = uuid.uuid4()
        org.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_organization_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
    ]
