# Generated by Django 6.0 on 2026-01-03 00:16

from django.db import migrations


def create_memberships_from_owners(apps, schema_editor):
    """
    Data migration: Create OrganizationMembership records for all existing org owners.
    This preserves the current owner relationships while enabling multi-admin support.
    """
    Organization = apps.get_model('orgs', 'Organization')
    OrganizationMembership = apps.get_model('orgs', 'OrganizationMembership')
    
    for org in Organization.objects.all():
        # Create OWNER membership for existing owner
        OrganizationMembership.objects.get_or_create(
            organization=org,
            user=org.owner,
            defaults={
                'role': 'OWNER',
                'is_active': True,
                'invited_by': None,  # Original owners weren't invited
            }
        )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Delete all memberships.
    Note: This will remove any additional admins added after migration.
    """
    OrganizationMembership = apps.get_model('orgs', 'OrganizationMembership')
    OrganizationMembership.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_organizationmembership'),
    ]

    operations = [
        migrations.RunPython(create_memberships_from_owners, reverse_migration),
    ]
