# Generated by Django 6.0 on 2026-01-05 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0009_alter_organization_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='subscription_is_active',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('TRIAL', 'Trial'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('INCOMPLETE', 'Incomplete')], default='TRIAL', help_text='Current subscription status', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_tier',
            field=models.CharField(choices=[('FREE_TRIAL', 'Free Trial (1 Campaign)'), ('PROFESSIONAL', 'Professional'), ('ENTERPRISE', 'Enterprise')], default='FREE_TRIAL', help_text='Current subscription tier', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='trial_campaigns_used',
            field=models.IntegerField(default=0, help_text='Number of campaigns used in free trial (max 1)'),
        ),
    ]
