# Generated by Django 6.0 on 2025-12-18 22:03

from django.db import migrations
import uuid


def populate_uuids(apps, schema_editor):
    Campaign = apps.get_model('campaigns', 'Campaign')
    for campaign in Campaign.objects.all():
        campaign.uuid = uuid.uuid4()
        campaign.save(update_fields=['uuid'])


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_uuids, migrations.RunPython.noop),
    ]
