# Generated by Django 6.0 on 2025-12-18 22:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_populate_campaign_uuids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
