# Generated by Django 6.0 on 2026-01-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigntarget',
            name='remediation_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When remediation training was assigned after clicking phishing link', null=True),
        ),
        migrations.AddField(
            model_name='campaigntarget',
            name='remediation_completed_at',
            field=models.DateTimeField(blank=True, help_text='When employee completed remediation acknowledgment', null=True),
        ),
    ]
