# Generated by Django 6.0 on 2026-01-03 23:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaigntarget_remediation_assigned_at_and_more'),
        ('orgs', '0009_alter_organization_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigntarget',
            name='remediation_assigned_at',
            field=models.DateTimeField(blank=True, help_text='When remediation training was assigned after clicking phishing link.', null=True),
        ),
        migrations.AlterField(
            model_name='campaigntarget',
            name='remediation_completed_at',
            field=models.DateTimeField(blank=True, help_text='When employee completed remediation acknowledgment.', null=True),
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('report_type', models.CharField(choices=[('QUARTERLY', 'Quarterly Compliance Report'), ('ANNUAL', 'Annual Security Training Report'), ('CAMPAIGN', 'Campaign-Specific Report'), ('AUDIT', 'Audit-Ready Package')], default='QUARTERLY', max_length=20)),
                ('period_start', models.DateField(help_text='Start date of reporting period')),
                ('period_end', models.DateField(help_text='End date of reporting period')),
                ('frameworks', models.CharField(default='HIPAA,HITECH,HITRUST,NIST,STATE_LAWS', help_text='Comma-separated list of included frameworks', max_length=200)),
                ('file_path', models.CharField(help_text='Path to generated PDF file', max_length=500)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('total_campaigns', models.IntegerField(default=0)),
                ('total_employees_trained', models.IntegerField(default=0)),
                ('overall_click_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remediation_completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='orgs.organization')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['organization', '-generated_at'], name='campaigns_c_organiz_f8142b_idx')],
            },
        ),
    ]
