# Generated by Django 6.0 on 2026-01-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_alter_campaigntarget_remediation_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='scenario_type',
            field=models.CharField(choices=[('PASSWORD_RESET', 'Password Reset'), ('BENEFITS_PORTAL', 'Benefits/Payroll Portal'), ('EMR_EHR_ACCESS', 'EMR/EHR System Access'), ('PATIENT_PORTAL', 'Patient Portal'), ('HIPAA_COMPLIANCE', 'HIPAA Compliance Notice'), ('MEDICAL_VENDOR', 'Medical Equipment/Vendor'), ('PHARMACY_RX', 'Pharmacy/Prescription'), ('INSURANCE_VERIFY', 'Insurance Verification'), ('HEALTH_ALERT', 'Health/Safety Alert'), ('IT_SUPPORT', 'IT Support Request'), ('PACKAGE_DELIVERY', 'Package Delivery'), ('EXECUTIVE_EMAIL', 'Executive/CEO Email'), ('OTHER', 'Other/General')], default='OTHER', help_text='The type of phishing scenario this template simulates', max_length=20),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='target_audience',
            field=models.CharField(choices=[('CLINICAL_STAFF', 'Clinical Staff (Doctors, Nurses)'), ('LAB_STAFF', 'Laboratory Staff'), ('ADMINISTRATIVE', 'Administrative Staff'), ('IT_STAFF', 'IT Staff'), ('BILLING_CODING', 'Billing/Coding Staff'), ('PHARMACY', 'Pharmacy Staff'), ('GENERAL', 'General/All Staff')], default='GENERAL', help_text='The intended audience/department for this template', max_length=20),
        ),
    ]
